services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2024.6
    ports:
      - "8123:8123"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ./config:/config
      - ./custom_components:/config/custom_components